export const AFFIRMATIONS = [
  "Rest is not laziness — it's how your body heals.",
  "You showed up today. That alone is enough.",
  "Small steps still count as moving forward.",
  "Being gentle with yourself is a form of strength.",
  "You don't have to feel perfect to have a good day.",
  "One good moment is a victory worth keeping.",
  "Your body is working hard, even when it doesn't feel like it.",
  "Progress isn't always visible, but it's always real.",
  "You are allowed to take your time.",
  "Even on hard days, you are exactly who you need to be.",
  "Your worth has nothing to do with your productivity.",
  "Today, even just breathing counts.",
  "Asking for help is one of the bravest things you can do.",
  "You carry a lot. It's okay to set some of it down.",
  "Healing isn't linear, and neither is life.",
  "A soft morning is still a morning worth having.",
  "Your energy is precious — spending it on yourself is always right.",
  "The hard days make the good ones sweeter.",
  "You are surrounded by people who care about you.",
  "A cozy day is a perfectly valid kind of day.",
  "You have made it through every hard day so far.",
  "Softness is not weakness. You are proof of that.",
  "Whatever you managed today — it was enough.",
  "You are more than your hard days.",
  "Joy lives in small things: a warm cup, a quiet moment, a kind word.",
  "Your presence in this world matters more than you know.",
  "It's okay to have needs. Everyone does.",
  "Even flowers close at night. Rest is part of blooming.",
  "Today is a new chance to be kind to yourself.",
  "You are doing better than you think.",
]

export const FACTS = [
  "Otters hold hands while sleeping so they don't drift apart. 🦦",
  "Cows have best friends and get stressed when separated from them. 🐄",
  "A group of flamingos is called a flamboyance. 🦩",
  "Honey never expires — 3000-year-old honey found in Egyptian tombs was still edible. 🍯",
  "Butterflies taste with their feet. 🦋",
  "Squirrels forget where they bury half their nuts — accidentally planting thousands of trees. 🌰",
  "The smell of rain has a name: petrichor. 🌧️",
  "Octopuses have three hearts and blue blood. 🐙",
  "A day on Venus is longer than a year on Venus. 🪐",
  "Trees in a forest share nutrients through underground fungal networks — the 'Wood Wide Web.' 🌳",
  "Sea otters have up to a million hairs per square inch — the densest fur of any animal. 🦦",
  "The average cloud weighs about 500,000 kg — roughly 100 elephants. ☁️",
  "Dolphins have names for each other — unique whistles they respond to. 🐬",
  "The Eiffel Tower grows about 15 cm taller in summer because metal expands in heat. 🗼",
  "Starfish have no blood — they pump seawater through their bodies instead. ⭐",
  "There is a jellyfish that is biologically immortal — it can revert to its juvenile state. 🪼",
  "A hummingbird's heart beats up to 1,200 times per minute. 🐦",
  "Each sunflower head contains up to 2,000 tiny individual flowers. 🌻",
  "Penguins propose to their mates with a pebble. 🐧",
  "Bananas are technically berries, but strawberries are not. 🍌",
  "A group of pugs is called a grumble. 🐾",
  "Cleopatra lived closer in time to the Moon landing than to the Great Pyramid. 🛸",
  "The world's oldest known living tree is over 5,000 years old. 🌲",
  "Baby elephants suck their trunks for comfort, just like human babies suck their thumbs. 🐘",
  "The Hawaiian alphabet has only 13 letters. 🌺",
  "A bolt of lightning is five times hotter than the surface of the Sun. ⚡",
  "The first oranges were green — the fruit was named after the color, not the other way around. 🍊",
  "There are more possible chess games than atoms in the observable universe. ♟️",
  "The world's largest living organism is a honey fungus in Oregon spanning 2.4 miles underground. 🍄",
  "Wombats produce cube-shaped droppings — the only animal that does this. 🐨",
]
